# THIS FILE IS AUTOMATICALLY GENERATED
# Project: C:\Users\boise\Documents\PSoC Creator\VoltMeter\CarVolt1.cydsn\CarVolt1.cyprj
# Date: Fri, 05 Mar 2021 13:40:13 GMT
#set_units -time ns
create_clock -name {ADC_intClock(FFB)} -period 250 -waveform {0 125} [list [get_pins {ClockBlock/ff_div_7}]]
create_clock -name {I2C_SCBCLK(FFB)} -period 125 -waveform {0 62.5} [list [get_pins {ClockBlock/ff_div_3}]]
create_clock -name {CyRouted1} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/dsi_in_0}]]
create_clock -name {CyILO} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/ilo}]]
create_clock -name {CyLFClk} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/lfclk}]]
create_clock -name {CyIMO} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyHFClk} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/hfclk}]]
create_clock -name {CySysClk} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/sysclk}]]
create_generated_clock -name {ADC_intClock} -source [get_pins {ClockBlock/hfclk}] -edges {1 7 13} [list]
create_generated_clock -name {Clock} -source [get_pins {ClockBlock/hfclk}] -edges {1 25 49} [list [get_pins {ClockBlock/udb_div_0}]]
create_generated_clock -name {I2C_SCBCLK} -source [get_pins {ClockBlock/hfclk}] -edges {1 3 7} [list]


# Component constraints for C:\Users\boise\Documents\PSoC Creator\VoltMeter\CarVolt1.cydsn\TopDesign\TopDesign.cysch
# Project: C:\Users\boise\Documents\PSoC Creator\VoltMeter\CarVolt1.cydsn\CarVolt1.cyprj
# Date: Fri, 05 Mar 2021 13:40:09 GMT
